# park_data.py

PARKS_DATA = [
    {
        "id": "acadia",
        "name": "Acadia National Park",
        "type": "National Park",
        "location": "Maine, USA",
        "address": "25 Visitor Center Rd, Bar Harbor, ME 04609",
        "latitude": 44.3386,
        "longitude": -68.2733,
        "region": "North America",
        "description": "Features a stunning rocky coastline, granite peaks, and historic carriage roads. Ideal for coastal hikes and scenic drives.",
        "activities": ["hiking", "biking", "boating", "wildlife watching", "stargazing", "photography", "scenic driving"],
        "scenery": ["mountains", "forests", "coasts", "lakes", "islands"],
        "image_url": "https://images.unsplash.com/photo-1693307481261-1725dbe5a61f?q=80&w=1373&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.8
    },
    {
        "id": "yosemite",
        "name": "Yosemite National Park",
        "type": "National Park",
        "location": "California, USA",
        "address": "9035 Village Dr, Yosemite Valley, CA 95389",
        "latitude": 37.8651,
        "longitude": -119.5383,
        "region": "North America",
        "description": "Famous for its giant sequoia trees, iconic granite cliffs like El Capitan and Half Dome, and stunning waterfalls.",
        "activities": ["hiking", "rock climbing", "photography", "wildlife watching", "camping", "waterfalls", "backpacking"],
        "scenery": ["mountains", "forests", "waterfalls", "valleys", "granite cliffs", "giant sequoias"],
        "image_url": "https://images.unsplash.com/photo-1518623380242-d992d3c57b37?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eW9zZW1pdGUlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
        "rating": 4.9
    },
    {
        "id": "zion",
        "name": "Zion National Park",
        "type": "National Park",
        "location": "Utah, USA",
        "address": "1 Zion Park Blvd, Springdale, UT 84767",
        "latitude": 37.2982,
        "longitude": -113.0263,
        "region": "North America",
        "description": "Known for its massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky. Offers challenging hikes like The Narrows.",
        "activities": ["hiking", "canyoning", "photography", "stargazing", "rock climbing", "backpacking"],
        "scenery": ["canyons", "rivers", "cliffs", "deserts", "slot canyons"],
        "image_url": "https://images.unsplash.com/photo-1443632864897-14973fa006cf?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.9
    },
    {
        "id": "yellowstone",
        "name": "Yellowstone National Park",
        "type": "National Park",
        "location": "Wyoming, Montana, Idaho, USA",
        "address": "2 Officers Row, Yellowstone National Park, WY 82190",
        "latitude": 44.4280,
        "longitude": -110.5885,
        "region": "North America",
        "description": "Home to geysers like Old Faithful, hot springs, and diverse wildlife including bison, elk, and bears. A geothermal wonderland.",
        "activities": ["hiking", "wildlife watching", "geothermal viewing", "camping", "fishing", "photography", "boating"],
        "scenery": ["geysers", "hot springs", "mountains", "forests", "lakes", "wildlife", "caldera"],
        "image_url": "https://images.unsplash.com/photo-1529439322271-42931c09bce1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eWVsbG93c3RvbmUlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D",
        "rating": 4.7
    },
    {
        "id": "grand_canyon",
        "name": "Grand Canyon National Park",
        "type": "National Park",
        "location": "Arizona, USA",
        "address": "S Entrance Rd, Grand Canyon Village, AZ 86023",
        "latitude": 36.0597,
        "longitude": -112.1119,
        "region": "North America",
        "description": "A mile-deep canyon carved by the Colorado River, offering breathtaking views, challenging hikes, and mule rides.",
        "activities": ["hiking", "mule rides", "rafting", "photography", "stargazing", "helicopter tours"],
        "scenery": ["canyons", "rivers", "deserts", "geological formations", "sunrise/sunset views"],
        "image_url": "https://images.unsplash.com/photo-1456425712190-0dd8c2b00156?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JhbmQlMjBjYW55b24lMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D",
        "rating": 4.9
    },
    {
        "id": "everglades",
        "name": "Everglades National Park",
        "type": "National Park",
        "location": "Florida, USA",
        "address": "40001 State Road 9336, Homestead, FL 33034",
        "latitude": 25.2866,
        "longitude": -80.8987,
        "region": "North America",
        "description": "A vast wetland ecosystem known for its unique wildlife, including alligators, manatees, and wading birds. Best explored by airboat or kayak.",
        "activities": ["boating", "kayaking", "wildlife watching", "fishing", "hiking", "bird watching", "airboat tours"],
        "scenery": ["wetlands", "mangroves", "wildlife", "sawgrass prairies"],
        "image_url": "https://images.unsplash.com/photo-1638552903242-4e3103f8ef69?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.5
    },
    {
        "id": "rocky_mountain",
        "name": "Rocky Mountain National Park",
        "type": "National Park",
        "location": "Colorado, USA",
        "address": "1000 US Hwy 36, Estes Park, CO 80517",
        "latitude": 40.3428,
        "longitude": -105.6836,
        "region": "North America",
        "description": "Features majestic mountain views, diverse wildlife, and Trail Ridge Road, the highest continuous paved road in North America.",
        "activities": ["hiking", "wildlife watching", "scenic driving", "fishing", "camping", "mountaineering", "snowshoeing"],
        "scenery": ["mountains", "alpine tundra", "forests", "lakes", "wildlife"],
        "image_url": "https://images.unsplash.com/photo-1600542158543-1faed2d1c05d?q=80&w=1631&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.8
    },
    {
        "id": "lincoln_memorial",
        "name": "Lincoln Memorial",
        "type": "National Memorial",
        "location": "Washington D.C., USA",
        "address": "2 Lincoln Memorial Cir NW, Washington, DC 20037",
        "latitude": 38.8893,
        "longitude": -77.0502,
        "region": "North America",
        "description": "An iconic American monument honoring the 16th U.S. President, Abraham Lincoln. Features a large seated sculpture of Lincoln.",
        "activities": ["sightseeing", "photography", "history learning"],
        "scenery": ["monuments", "city views", "reflecting pool"],
        "image_url": "https://images.unsplash.com/photo-1586526061780-64f99789d68a?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.7
    },
    {
        "id": "mount_rushmore",
        "name": "Mount Rushmore National Memorial",
        "type": "National Memorial",
        "location": "South Dakota, USA",
        "address": "13000 SD-244, Keystone, SD 57751",
        "latitude": 43.8791,
        "longitude": -103.4591,
        "region": "North America",
        "description": "Features colossal sculptures of four U.S. presidents carved into the granite face of Mount Rushmore.",
        "activities": ["sightseeing", "photography", "history learning", "hiking"],
        "scenery": ["mountains", "sculptures", "forests"],
        "image_url": "https://images.unsplash.com/photo-1597054420938-5e6909089a4b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.6
    },
    {
        "id": "plitvice_lakes",
        "name": "Plitvice Lakes National Park",
        "type": "National Park",
        "location": "Croatia",
        "address": "Plitvička Jezera, Croatia",
        "latitude": 44.8653,
        "longitude": 15.5820,
        "region": "Europe",
        "description": "Known for a chain of 16 terraced lakes, joined by waterfalls, that extend into a limestone canyon. Walkways and hiking trails wind around and across the water.",
        "activities": ["hiking", "photography", "boating", "waterfalls"],
        "scenery": ["lakes", "waterfalls", "forests", "canyons"],
        "image_url": "https://images.unsplash.com/photo-1523887531304-19f3631397f0?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.9
    },
    {
        "id": "uluru_kata_tjuta",
        "name": "Uluru-Kata Tjuta National Park",
        "type": "National Park",
        "location": "Northern Territory, Australia",
        "address": "Uluru Rd, Uluru NT 0872, Australia",
        "latitude": -25.3444,
        "longitude": 131.0369,
        "region": "Australia/Oceania",
        "description": "Home to Uluru (Ayers Rock), a massive sandstone monolith, and the Kata Tjuta (The Olgas) rock domes. Sacred to Indigenous Australians.",
        "activities": ["cultural tours", "hiking", "stargazing", "sunrise/sunset views", "photography"],
        "scenery": ["deserts", "rock formations", "cultural sites"],
        "image_url": "https://images.unsplash.com/photo-1591610364828-419bf4b51566?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "rating": 4.8
    }
]

AVAILABLE_ACTIVITIES = sorted(list(set(activity for park in PARKS_DATA for activity in park.get("activities", []))))
AVAILABLE_SCENERY = sorted(list(set(scenery_type for park in PARKS_DATA for scenery_type in park.get("scenery", []))))
AVAILABLE_REGIONS = sorted(list(set(park.get("region", "Other") for park in PARKS_DATA)))
AVAILABLE_PARK_TYPES = sorted(list(set(park.get("type", "Other") for park in PARKS_DATA)))